# Name your project! Project names should contain only lowercase characters
# and underscores.
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------------------
# Snowflake-specific settings
# ---------------------------------------------------------------------

# Force quoting so numeric table names like "2_CUSTOMERS" always work
quoting:
  database: true
  schema: true
  identifier: true

# ---------------------------------------------------------------------
# Model configurations
# ---------------------------------------------------------------------

models:
  my_new_project:

    # Staging models: lightweight views on top of sources
    staging:
      +materialized: view

    # Mart models: dimensions & facts as tables
    marts:
      +materialized: table
