version: 2

models:

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: geography_id
        tests:
          - not_null

  - name: stg_geography
    columns:
      - name: geography_id
        tests:
          - not_null
          - unique

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

      - name: product_sub_category_id
        tests:
          - not_null

  - name: stg_sales
    columns:
      - name: sales_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

      - name: order_date_id
        tests:
          - not_null
